exclude: '.docs|node_modules|migrations|.git|.tox|venv'
default_stages: [commit]
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0

    hooks:
    -   id: isort
        exclude: migrations/
-   repo: https://github.com/myint/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: detect-private-key
    -   id: check-case-conflict
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/dhruvmanila/remove-print-statements
    rev: v0.5.2
    hooks:
    - id: remove-print-statements
      args: ['--verbose']
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args:
            - "--max-line-length=120"
        exclude: migrations/
        additional_dependencies:
            - flake8-bugbear
            - flake8-comprehensions
            - flake8-simplify
-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.14.1
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.2"]
