# Generated by Django 4.2.6 on 2023-10-25 18:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("conditions", ckeditor.fields.RichTextField()),
                ("points", models.DecimalField(decimal_places=2, max_digits=2)),
                ("repeat_points", models.DecimalField(decimal_places=2, max_digits=2)),
                (
                    "iterations",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The required number of iterations to complete the exercise",
                    ),
                ),
                (
                    "topic_type",
                    models.CharField(
                        choices=[
                            ("grammar", "grammar"),
                            ("audition", "audition"),
                            ("vocabulary", "vocabulary"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_reset_points_after_error", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("code", models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_grammar_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_vocabulary_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_audition_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("total_passed_grammar_topics", models.PositiveIntegerField(default=0)),
                (
                    "total_passed_audition_topics",
                    models.PositiveIntegerField(default=0),
                ),
                ("total_passed_words", models.PositiveIntegerField(default=0)),
                ("total_passed_word_sets", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "is_default")},
            },
        ),
        migrations.CreateModel(
            name="UserDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_grammar_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_vocabulary_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_audition_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_passed_grammar_topics", models.PositiveIntegerField(default=0)),
                (
                    "total_passed_audition_topics",
                    models.PositiveIntegerField(default=0),
                ),
                ("total_passed_words", models.PositiveIntegerField(default=0)),
                ("total_passed_word_sets", models.PositiveIntegerField(default=0)),
                ("is_old_material_mastered", models.BooleanField(default=False)),
                ("is_new_material_learned", models.BooleanField(default=False)),
                (
                    "user_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="courses.usercourse",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="from_language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_language_courses",
                to="courses.language",
                verbose_name="Native language of student",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="to_language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="studied_language_courses",
                to="courses.language",
                verbose_name="Studied language",
            ),
        ),
    ]
