# Generated by Django 4.2.7 on 2023-11-11 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="from_language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_language_courses",
                to="courses.language",
                verbose_name="Native language of student",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="to_language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="studied_language_courses",
                to="courses.language",
                verbose_name="Studied language",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercourse",
            unique_together={("user", "is_default")},
        ),
    ]
