version: '3'

services:
  web: &web
    image: web-backend
    restart: always
    build:
      context: ../
      dockerfile: ".build/Dockerfile"
    command: /bin/sh -c "python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - ../:/project
      - ../static/:/project/static/
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - ../.envs/.prod/.django
      - ../.envs/.prod/.secret

  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    <<: *web
    image: web-celery
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ..:/project:z
    ports: [ ]
    command: celery -A core.celery_app worker -l INFO
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_db_name
      - POSTGRES_USER=app_db_user
      - POSTGRES_PASSWORD=app_db_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5435:5432"
  nginx:
    image: nginx:latest
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../static/:/project/static/
      - ../.envs/.prod/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
