# Generated by Django 4.2.6 on 2023-10-25 18:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=200)),
                ("definition", models.TextField()),
                ("transcription", models.CharField(max_length=200)),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("pronoun", "Pronoun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("preposition", "Preposition"),
                            ("conjunction", "Conjunction"),
                            ("interjection", "Interjection"),
                            ("article", "Article"),
                            ("determiner", "Determiner"),
                            ("particle", "Particle"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.language",
                    ),
                ),
                ("synonyms", models.ManyToManyField(blank=True, to="vocabulary.word")),
            ],
        ),
        migrations.CreateModel(
            name="WordExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField()),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocabulary.word",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=200)),
                ("definition", models.TextField()),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
                ("levels", models.ManyToManyField(blank=True, to="courses.level")),
                ("words", models.ManyToManyField(blank=True, to="vocabulary.word")),
            ],
        ),
        migrations.CreateModel(
            name="WordExampleTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField()),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocabulary.wordexample",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_level",
                    models.CharField(
                        choices=[
                            ("started", "started"),
                            ("in_progress", "in_progress"),
                            ("learned", "learned"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="courses.usercourse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.language",
                    ),
                ),
                (
                    "user_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictionaries",
                        to="courses.usercourse",
                    ),
                ),
                ("words", models.ManyToManyField(blank=True, to="vocabulary.word")),
            ],
        ),
    ]
