# Generated by Django 4.2.7 on 2023-11-11 10:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditionExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, default=None, null=True)),
                ("conditions", ckeditor.fields.RichTextField()),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="You can overwrite default value of points for particular exercise",
                        max_digits=5,
                    ),
                ),
                (
                    "iterations",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The required number of iterations to complete the exercise",
                    ),
                ),
            ],
            options={
                "ordering": ("-points",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditionExerciseVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("options", models.JSONField()),
                ("answer", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="AuditionSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField()),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditionTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField()),
                ("slug", models.SlugField(default=None, null=True, unique=True)),
                ("required_points", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserAuditionExerciseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts_count", models.PositiveIntegerField(default=0)),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Earned points"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAuditionTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Earned points"
                    ),
                ),
                ("is_theory_read", models.BooleanField(default=False)),
                ("is_passed", models.BooleanField(default=False)),
                (
                    "learning_level",
                    models.CharField(
                        choices=[
                            ("started", "started"),
                            ("in_progress", "in_progress"),
                            ("learned", "learned"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
