# Generated by Django 4.2.7 on 2023-11-11 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("audition", "0002_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userauditionexerciseattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userauditionexerciseattempt",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="audition.auditionexercisevariant",
            ),
        ),
        migrations.AddField(
            model_name="auditiontopic",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="audition.auditionsection",
            ),
        ),
        migrations.AddField(
            model_name="auditionsection",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="auditionsection",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.level",
            ),
        ),
        migrations.AddField(
            model_name="auditionexercisevariant",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="audition.auditionexercise",
            ),
        ),
        migrations.AddField(
            model_name="auditionexercise",
            name="exercise_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.exercisetype",
            ),
        ),
        migrations.AddField(
            model_name="auditionexercise",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="audition.auditiontopic",
            ),
        ),
    ]
