# Generated by Django 4.2.6 on 2023-10-25 18:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="You can overwrite default value of points for particular exercise",
                        max_digits=2,
                    ),
                ),
                ("conditions", ckeditor.fields.RichTextField()),
                (
                    "iterations",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The required number of iterations to complete the exercise",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.exercisetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GrammarExerciseVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("options", models.JSONField()),
                ("answer", models.JSONField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="grammar.grammarexercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrammarSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.level",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GrammarTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required_points", models.PositiveSmallIntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grammar.grammarsection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserGrammarTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="Earned points"
                    ),
                ),
                ("is_theory_read", models.BooleanField(default=False)),
                ("is_passed", models.BooleanField(default=False)),
                (
                    "learning_level",
                    models.CharField(
                        choices=[
                            ("started", "started"),
                            ("in_progress", "in_progress"),
                            ("learned", "learned"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercises",
                    models.ManyToManyField(blank=True, to="courses.exercisetype"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grammar.grammartopic",
                    ),
                ),
                (
                    "user_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_topics",
                        to="courses.usercourse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserGrammarExerciseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts_count", models.PositiveIntegerField(default=0)),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="Earned points"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grammar.grammarexercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grammar.grammarexercisevariant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="grammarexercise",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grammar.grammartopic",
            ),
        ),
    ]
